"""
Global Project Configuration
----------------------------
Centralizes constants, directory paths, and model hyperparameters.
Ensures reproducibility and manages relative paths for portability.
"""

import os
import torch
from pathlib import Path

# --- 1. SYSTEM & REPRODUCIBILITY SETUP ---
# Automatically detect the project root directory (where this file is located)
PROJECT_ROOT = Path(__file__).parent.resolve()

# Automatic device selection (GPU if available, else CPU)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 42
NUM_WORKERS = os.cpu_count()  # Optimize data loading based on available CPU cores

# --- 2. EXPERIMENT DEFINITION ---
# Name of the carrier/scenario to analyze
CURRENT_CARRIER = "Carrier_C4_9435"

# --- 3. PATH MANAGEMENT ---
# All paths are relative to PROJECT_ROOT to ensure the code runs on any machine

# Data Directories
DATA_ROOT = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_ROOT / "raw" / CURRENT_CARRIER
PROCESSED_DATA_DIR = DATA_ROOT / "processed" / CURRENT_CARRIER

# Split Subdirectories (generated by 00_prepare_data.py)
TRAIN_VAL_DIR = PROCESSED_DATA_DIR / "train_val"
TEST_DIR = PROCESSED_DATA_DIR / "test"
UNLABELED_DIR = RAW_DATA_DIR / "SIN_CLASIFICAR"  # Unlabeled data is not split

# Output Directories
ARTIFACTS_DIR = PROJECT_ROOT / "results" / CURRENT_CARRIER
CHECKPOINTS_DIR = ARTIFACTS_DIR / "checkpoints"
PLOTS_DIR = ARTIFACTS_DIR / "figures"
PSEUDO_LABEL_DIR = ARTIFACTS_DIR / "pseudo_labels"

# Specific Files
METRICS_FILE = ARTIFACTS_DIR / "metrics_summary.xlsx"

# Ensure key output directories exist
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
CHECKPOINTS_DIR.mkdir(parents=True, exist_ok=True)

# --- 4. IMAGE PROCESSING PARAMETERS ---
IMG_SIZE = (100, 100)  # (Height, Width)
# Note: NUM_CLASSES is inferred dynamically from folder structure

# --- 5. MODEL ZOO & HYPERPARAMETERS ---
# Configuration dictionary for experimentation
TRAIN_PARAMS = {
    "cnn_paper": {
        "MODEL_NAME": "cnn_paper",
        "BATCH_SIZE": 32,
        "EPOCHS": 300,
        "LR": 1e-3,
        "MOMENTUM": 0.9,
        "WEIGHT_DECAY": 0.0,
        "USE_COSINE_LR": True,
        "PATIENCE": 12,
        "RESIZE_224": False,
    },
    "cnn_paper_L2": {
        "MODEL_NAME": "cnn_paper_L2",
        "BATCH_SIZE": 32,
        "EPOCHS": 300,
        "LR": 1e-3,
        "MOMENTUM": 0.9,
        "WEIGHT_DECAY": 1e-4,
        "USE_COSINE_LR": True,
        "PATIENCE": 12,
        "RESIZE_224": False,
    },
    "resnet50": {
        "MODEL_NAME": "resnet50",
        "BATCH_SIZE": 32,
        "EPOCHS": 300,
        "LR": 1e-3,
        "MOMENTUM": 0.9,
        "WEIGHT_DECAY": 1e-4,
        "USE_COSINE_LR": True,
        "PATIENCE": 15,
        "RESIZE_224": True,
        "USE_PRETRAIN": True,
    },
    "resnet18": {
        "MODEL_NAME": "resnet18",
        "BATCH_SIZE": 32,
        "EPOCHS": 300,
        "LR": 1e-3,
        "MOMENTUM": 0.9,
        "WEIGHT_DECAY": 1e-4,
        "USE_COSINE_LR": True,
        "PATIENCE": 15,
        "RESIZE_224": True,
        "USE_PRETRAIN": True,
    }
}

# --- 6. TRAINING & STOPPING CRITERIA ---
EARLY_STOPPING_CONFIG = {
    "monitor": "f1_macro",
    "min_delta": 0.002,
    "mode": "max"
}

CLIP_MAX_NORM = 10.0
ETA_MIN_FACTOR = 0.1